// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Demo.Core.Data;
using Demo.Core.DomainModel.App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Demo.Core.Data.Configurations
{
    public partial class DeviceFirmwareDeviceModelsConfiguration : IEntityTypeConfiguration<DeviceFirmwareDeviceModels>
    {
        public void Configure(EntityTypeBuilder<DeviceFirmwareDeviceModels> entity)
        {
            entity.ToTable("device_firmware_device_models", "shared");

            entity.HasIndex(e => e.DeviceModelId, "device_firmware_device_models_device_model_id_fkey");

            entity.HasIndex(e => new { e.FirmwareId, e.DeviceModelId }, "device_firmware_device_models_firmware_id_device_model_id_idx")
                .IsUnique();

            entity.HasIndex(e => e.FirmwareId, "device_firmware_device_models_firmware_id_idx");

            entity.HasIndex(e => e.MaxSuppVersionId, "device_firmware_device_models_max_supp_version_id_idx");

            entity.HasIndex(e => e.MinSuppVersionId, "device_firmware_device_models_min_supp_version_id_idx");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.CreatedAt)
                .HasColumnName("created_at")
                .HasDefaultValueSql("'-infinity'::timestamp with time zone");

            entity.Property(e => e.DeviceModelId).HasColumnName("device_model_id");

            entity.Property(e => e.FirmwareId).HasColumnName("firmware_id");

            entity.Property(e => e.MaxSuppVersionId).HasColumnName("max_supp_version_id");

            entity.Property(e => e.MinSuppVersionId).HasColumnName("min_supp_version_id");

            entity.Property(e => e.ModifiedAt).HasColumnName("modified_at");

            entity.HasOne(d => d.DeviceModel)
                .WithMany(p => p.DeviceFirmwareDeviceModels)
                .HasForeignKey(d => d.DeviceModelId)
                .HasConstraintName("device_firmware_device_models_device_model_id_fkey");

            entity.HasOne(d => d.Firmware)
                .WithMany(p => p.DeviceFirmwareDeviceModels)
                .HasForeignKey(d => d.FirmwareId)
                .HasConstraintName("device_firmware_device_models_firmware_id_fkey");

            entity.HasOne(d => d.MaxSuppVersion)
                .WithMany(p => p.DeviceFirmwareDeviceModelsMaxSuppVersion)
                .HasForeignKey(d => d.MaxSuppVersionId)
                .HasConstraintName("device_firmware_device_models_max_supp_version_id_fkey");

            entity.HasOne(d => d.MinSuppVersion)
                .WithMany(p => p.DeviceFirmwareDeviceModelsMinSuppVersion)
                .HasForeignKey(d => d.MinSuppVersionId)
                .HasConstraintName("device_firmware_device_models_min_supp_version_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DeviceFirmwareDeviceModels> entity);
    }
}
