// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Demo.Core.Data;
using Demo.Core.DomainModel.App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Demo.Core.Data.Configurations
{
    public partial class DeviceFirmwaresConfiguration : IEntityTypeConfiguration<DeviceFirmwares>
    {
        public void Configure(EntityTypeBuilder<DeviceFirmwares> entity)
        {
            entity.ToTable("device_firmwares", "shared");

            entity.HasIndex(e => new { e.Vendor, e.Key }, "device_firmwares_vendor_key_idx")
                .IsUnique();

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.CreatedAt)
                .HasColumnName("created_at")
                .HasDefaultValueSql("'-infinity'::timestamp with time zone");

            entity.Property(e => e.Description)
                .HasColumnType("character varying")
                .HasColumnName("description");

            entity.Property(e => e.Key)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("key")
                .HasDefaultValueSql("''::character varying");

            entity.Property(e => e.ModifiedAt).HasColumnName("modified_at");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("name");

            entity.Property(e => e.Vendor)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("vendor");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DeviceFirmwares> entity);
    }
}
