// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Demo.Core.Data;
using Demo.Core.DomainModel.App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Demo.Core.Data.Configurations
{
    public partial class ObjectUserRolesConfiguration : EntityTypeConfiguration<ObjectUserRoles>
    {
        public void Configure(EntityTypeBuilder<ObjectUserRoles> entity)
        {
            entity.ToTable("object_user_roles", "shared");

            entity.HasIndex(e => new { e.ObjectType, e.ObjectId, e.UserId }, "object_user_roles_object_type_object_id_user_id_idx")
                .IsUnique();

            entity.HasIndex(e => e.UserId, "object_user_roles_user_id_idx");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.CreatedAt).HasColumnName("created_at");

            entity.Property(e => e.ModifiedAt).HasColumnName("modified_at");

            entity.Property(e => e.ObjectId)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("object_id");

            entity.Property(e => e.ObjectType)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("object_type");

            entity.Property(e => e.Role)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("role");

            entity.Property(e => e.UserId)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("user_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ObjectUserRoles> entity);
    }
}
