// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Demo.Core.Data;
using Demo.Core.DomainModel.App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Demo.Core.Data.Configurations
{
    public partial class UsersConfiguration : EntityTypeConfiguration<Users>
    {
        public void Configure(EntityTypeBuilder<Users> entity)
        {
            entity.ToTable("users", "shared");

            entity.HasIndex(e => e.Email, "users_email_idx")
                .IsUnique();

            entity.Property(e => e.Id)
                .HasColumnType("character varying")
                .HasColumnName("id");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("email");

            entity.Property(e => e.IsAdmin).HasColumnName("is_admin");

            entity.Property(e => e.LastLoginAt).HasColumnName("last_login_at");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Users> entity);
    }
}
