// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Demo.Core.Data;
using Demo.Core.DomainModel.App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Demo.Core.Data.Configurations
{
    public partial class VirtualLaboratoriesConfiguration : EntityTypeConfiguration<VirtualLaboratories>
    {
        public void Configure(EntityTypeBuilder<VirtualLaboratories> entity)
        {
            entity.ToTable("virtual_laboratories", "shared");

            entity.HasIndex(e => new { e.TenantId, e.Name }, "virtual_laboratories_tenant_id_name_idx")
                .IsUnique();

            entity.Property(e => e.Id)
                .HasColumnType("character varying")
                .HasColumnName("id");

            entity.Property(e => e.AccessKey)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("access_key")
                .HasDefaultValueSql("''::character varying");

            entity.Property(e => e.CreatedAt).HasColumnName("created_at");

            entity.Property(e => e.Description)
                .HasColumnType("character varying")
                .HasColumnName("description");

            entity.Property(e => e.ModifiedAt).HasColumnName("modified_at");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("name");

            entity.Property(e => e.TenantId).HasColumnName("tenant_id");

            entity.HasOne(d => d.Tenant)
                .WithMany(p => p.VirtualLaboratories)
                .HasForeignKey(d => d.TenantId)
                .HasConstraintName("virtual_laboratories_tenant_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VirtualLaboratories> entity);
    }
}
