// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Demo.Core.Data;
using System;
using System.Collections.Generic;

namespace Demo.Core.DomainModel.App
{
    public partial class DeviceFirmwares: BaseEntity
    {
        public DeviceFirmwares()
        {
            DeviceFirmwareDeviceModels = new HashSet<DeviceFirmwareDeviceModels>();
            DeviceFirmwareVersions = new HashSet<DeviceFirmwareVersions>();
        }

        public Guid Id { get; set; }
        public string Vendor { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Key { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }

        public virtual ICollection<DeviceFirmwareDeviceModels> DeviceFirmwareDeviceModels { get; set; }
        public virtual ICollection<DeviceFirmwareVersions> DeviceFirmwareVersions { get; set; }
    }
}