// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Demo.Core.DomainModel.App
{
    public partial class DeviceTwinProperties
    {
        public long Id { get; set; }
        public string ConnectionStatus { get; set; }
        public string ConnectionStatusUpdateSeqNo { get; set; }
        public DateTime? ConnectionStatusUpdatedAt { get; set; }
        public string ReportedProperties { get; set; }
        public string ReportedPropertiesCompressionType { get; set; }
        public string ReportedPropertiesSeqNo { get; set; }
        public DateTime? ReportedPropertiesUpdatedAt { get; set; }

        public virtual Devices IdNavigation { get; set; }
    }
}