// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Demo.Core.DomainModel.App
{
    public partial class DeviceModels
    {
        public DeviceModels()
        {
            DeviceFirmwareDeviceModels = new HashSet<DeviceFirmwareDeviceModels>();
        }

        public Guid Id { get; set; }
        public string Vendor { get; set; }
        public string Identifier { get; set; }
        public string Version { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Akz { get; set; }

        public virtual ICollection<DeviceFirmwareDeviceModels> DeviceFirmwareDeviceModels { get; set; }
    }
}