// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Demo.Core.Data;
using System;
using System.Collections.Generic;

namespace Demo.Core.DomainModel.App
{
    public partial class DeviceFirmwareVersions : BaseEntity
    {
        public DeviceFirmwareVersions()
        {
            DeviceFirmwareDeviceModelsMaxSuppVersion = new HashSet<DeviceFirmwareDeviceModels>();
            DeviceFirmwareDeviceModelsMinSuppVersion = new HashSet<DeviceFirmwareDeviceModels>();
        }

        public Guid Id { get; set; }
        public Guid FirmwareId { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public DateTime? PublishedAt { get; set; }
        public DateTime? ReleasedAt { get; set; }

        public virtual DeviceFirmwares Firmware { get; set; }
        public virtual ICollection<DeviceFirmwareDeviceModels> DeviceFirmwareDeviceModelsMaxSuppVersion { get; set; }
        public virtual ICollection<DeviceFirmwareDeviceModels> DeviceFirmwareDeviceModelsMinSuppVersion { get; set; }
    }
}