// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Demo.Core.Data;
using System;
using System.Collections.Generic;

namespace Demo.Core.DomainModel.App
{
    public partial class ObjectUserRoles : BaseEntity
    {
        public Guid Id { get; set; }
        public string ObjectType { get; set; }
        public string ObjectId { get; set; }
        public string UserId { get; set; }
        public string Role { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}