// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Demo.Core.Data;
using System;
using System.Collections.Generic;

namespace Demo.Core.DomainModel.App
{
    public partial class Tenants : BaseEntity
    {
        public Tenants()
        {
            TenantKeyAccountAssignments = new HashSet<TenantKeyAccountAssignments>();
            VirtualLaboratories = new HashSet<VirtualLaboratories>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string Description { get; set; }
        public string ProfileImageId { get; set; }
        public string ProfileImageUri { get; set; }

        public virtual ICollection<TenantKeyAccountAssignments> TenantKeyAccountAssignments { get; set; }
        public virtual ICollection<VirtualLaboratories> VirtualLaboratories { get; set; }
    }
}