// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Demo.Core.Data;
using System;
using System.Collections.Generic;

namespace Demo.Core.DomainModel.App
{
    public partial class VsfilesObjectTypeIdMappingEntries : BaseEntity
    {
        public string ProductInformationFileType { get; set; }
        public long VsfilesObjectTypeId { get; set; }
    }
}